FROM node:12.2.0-alpine as builder

RUN apk update && apk add --no-cache make git python3 py3-pip autoconf g++ libc6-compat libjpeg-turbo-dev libpng-dev nasm

WORKDIR /usr/src/app
COPY yarn.lock package.json ./

RUN yarn install

COPY . /usr/src/app
WORKDIR /usr/src/app
RUN  yarn build

FROM scratch AS export-stage
COPY --from=builder /usr/src/app/public /